[tool.black]
line-length = 88
target-version = ["py311"]
skip-string-normalization = false

[tool.ruff]
line-length = 88
target-version = "py311"
select = ["E", "F"]
ignore = ["E501"]
fix = true

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
strict_optional = true
disallow_untyped_defs = true
disallow_untyped_calls = false
no_implicit_optional = true
check_untyped_defs = true
ignore_missing_imports = true
explicit_package_bases = true
mypy_path = "."

[tool.isort]
profile = "black"
line_length = 88
